kratos:
  config:
    # Mandatory values
    dsn: postgres://ory:p4ssw0rd@pg-sqlproxy-gcloud-sqlproxy:5432/db
    secrets:
      session:
        - dolore occaecat nostrud Ut
        - sit et commodoaute ut voluptate consectetur Duis

    # Optional values
    log:
      level: trace
