kratos:
  config:
    # Mandatory values
    dsn: postgres://ory:p4ssw0rd@ory-postgresql:5432/kratos
    secrets:
      session:
        - dolore occaecat nostrud Ut
        - sit et commodoaute ut voluptate consectetur Duis

    # Optional values
    log:
      level: trace
